server:
  port: 8080

spring:
  application:
    name: chef-on-minutes
  datasource:
    url: jdbc:h2:mem:chefdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  cors:
    allowed-origins: http://localhost:5173
