server:
  port: ${PORT:8080}

spring:
  application:
    name: chef-on-minutes
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:5173}
